version: 2.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: quay.io/haskell_works/stack-build-cabal:2018-01-29

    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - dot-stack
      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}

      - run: stack setup
      - run: stack build --test --no-run-tests --haddock --no-haddock-deps

      - run: ./scripts/copy-docs.sh

      - run:
          name: Running unit tests
          command: stack test

      - save_cache:
          key: dot-stack-base
          paths:
            - ~/.stack

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack

      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/project/.stack-work

      - store_artifacts:
          path: /tmp/doc
