name: hw-kafka-avro
version: '2.1.0'
synopsis: Avro support for Kafka infrastructure
description: Please see README.md
category: Services
author: Alexey Raga
maintainer: alexey.raga@gmail.com
copyright: Alexey Raga
license: BSD3
github: haskell-works/hw-kafka-avro
extra-source-files:
- README.md
dependencies:
- aeson
- binary
- bytestring
- cache
- containers
- errors
- hashable
- http-client
- mtl
- pure-zlib >=0.6
- semigroups
- text
- transformers
- unordered-containers
library:
  source-dirs: src
  exposed-modules:
  - Kafka.Avro
  - Kafka.Avro.Decode
  - Kafka.Avro.Encode
  - Kafka.Avro.SchemaRegistry
  dependencies:
  - avro >=0.4
  - base >=4.7 && <5
  - wreq
  - lens
  - http-types
  - tagged
executables:
  kafka-avro-example:
    main: Main.hs
    source-dirs: example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - avro
    - base
    - hw-kafka-avro
    when:
    - condition: ! '!(flag(examples))'
      buildable: false
tests:
  kafka-avro-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - avro
    - base
    - hw-kafka-avro
    - hspec
flags:
  examples:
    description: Also compile examples
    manual: true
    default: false
