defaults: &defaults
  working_directory: ~/build
  docker:
    - image: quay.io/haskell_works/stack-build-cabal

    # - image: confluentinc/cp-zookeeper:3.1.2
    #   environment:
    #     ZOOKEEPER_CLIENT_PORT: 2181

    # - image: confluentinc/cp-kafka:3.1.2
    #   environment:
    #     KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
    #     KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
    #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  steps:
    - checkout

    - restore_cache:
        keys:
          - dot-stack-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.yaml" }}
          - dot-stack-{{ arch }}-{{ .Environment.CIRCLE_JOB }}

    - restore_cache:
        key: stack-work-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.yaml" }}

    - run: stack setup --resolver ${LTS} ${STACK_ARGS}
    - run: stack build --test --no-run-tests --haddock --no-haddock-deps --resolver ${LTS} ${STACK_ARGS}

    - save_cache:
        key: dot-stack-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/.stack

    - run:
        name: Running unit tests
        command: stack test --resolver ${LTS} ${STACK_ARGS}

    - save_cache:
        key: dot-stack-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.yaml" }}
        paths:
          - ~/.stack

    - save_cache:
        key: stack-work-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.yaml" }}
        paths: ~/build/.stack-work

version: 2.0
jobs:
  lts-7:
    environment:
      - LTS: "lts-7"
    <<: *defaults

  lts-9:
    environment:
      - LTS: "lts-9"
    <<: *defaults

  lts-11:
    environment:
      - LTS: "lts-11"
    <<: *defaults

  nightly:
    environment:
      - LTS: "nightly"
      - STACK_ARGS: "--stack-yaml=stack-nightly.yaml"
    <<: *defaults

  release:
    working_directory: ~/build
    docker:
      - image: quay.io/haskell_works/stack-build-cabal

    steps:
      - checkout

      - run:
          name: Making a release
          command: ./scripts/release


workflows:
  version: 2
  multiple-ghcs:
    jobs:
      # - lts-7
      - lts-9
      - lts-11
      # - nightly
      - release:
          requires:
            # - lts-7
            - lts-9
            - lts-11
            # - nightly
          filters:
            branches:
              only: master

